"""initial

Revision ID: 04a14270fae2
Revises: 
Create Date: 2026-04-08 02:45:24.212101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a14270fae2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_activity_at', sa.String(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_consolidated_position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('memory_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'category', 'key', name='uq_memory_session_category_key')
    )
    op.create_index('idx_memory_category', 'memory_entries', ['session_key', 'category'], unique=False)
    op.create_index('idx_memory_session', 'memory_entries', ['session_key'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('tool_results', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'position', name='uq_messages_session_position')
    )
    op.create_index('idx_messages_position', 'messages', ['session_key', 'position'], unique=False)
    op.create_index('idx_messages_session', 'messages', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_index('idx_messages_position', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_memory_session', table_name='memory_entries')
    op.drop_index('idx_memory_category', table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_table('sessions')
    # ### end Alembic commands ###
