"""initial

Revision ID: 8090532e2a41
Revises: 
Create Date: 2026-04-11 15:39:18.932084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8090532e2a41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summarized_through_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.key'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summarized_through_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_histories_session_id', 'histories', ['session_key', 'id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(), nullable=False),
    sa.Column('messages_json', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session', 'messages', ['session_key'], unique=False)
    op.create_table('sessions',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('current_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_history_id'], ['histories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('subagent_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('subagent_session_key', sa.String(), nullable=False),
    sa.Column('origin_channel', sa.String(), nullable=False),
    sa.Column('origin_chat_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_key'], ['sessions.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subagent_sessions_label_parent', 'subagent_sessions', ['label', 'parent_key'], unique=True)
    op.create_index('idx_subagent_sessions_parent', 'subagent_sessions', ['parent_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subagent_sessions_parent', table_name='subagent_sessions')
    op.drop_index('idx_subagent_sessions_label_parent', table_name='subagent_sessions')
    op.drop_table('subagent_sessions')
    op.drop_table('sessions')
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_histories_session_id', table_name='histories')
    op.drop_table('histories')
    # ### end Alembic commands ###
